services:
    nessus:
        image: tenable/nessus:latest-ubuntu
        restart: always
        container_name: nessus
        ports:
            - 8834:8834
        volumes:
            - nessus-data:/opt/nessus
    cups:
        image: vulhub/cups-browsed:2.0.1
        ports:
            - 631:631
    ubuntu:
        image: afryie/ssh-ubuntu2022:latest
        ports:
            - 2222:22
volumes:
    nessus-data:
